version: '2'
services:
  gateway:
    build: ./app/
    ports:
      - "3010:3000"
    volumes:
      - "./app:/usr/src/app"
      - "/usr/src/app/node_modules"
    links:
      - "gateway_mongo_db"
  gateway_mongo_db:
    image: mongo:3.4.4
    ports: 
      - "27020:27017"
    volumes:
      - "./data:/data/db"
